name: Test

on: ["push"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Run tests
        run: go test -v -race -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
        working-directory: app
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Submit coverage
        run: goveralls -coverprofile=$GITHUB_WORKSPACE/profile.cov -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: app
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          working-directory: app
  # golangci:
  #     runs-on: ubuntu-latest
  #     steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: '1.19'
  #     - name: Run linters
  #       uses: golangci/golangci-lint-action@v3
  #       with:
  #         version: v1.29
  #         working-directory: app